# Site
name: "Affiliates Theme for Jekyll"
title: "Affiliates Theme for Jekyll"
description: "Jekyll Theme for Blogging"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/my_face_small.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'mp.papinski@gmail.com'
disqus: 'https-mikepapinski-github-io-sleek'
sharethis: ''

# Authors
authors:
  MikePapinski:
    name: MikePapinski
    display_name: Mike Papinski
    gravatar: my_avatar.png
    email: mp.papinski@@gmail.com
    web: https://mikepapinski.github.io
    description: "Main author of Mike Papinski Lab."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge