# Site
name: "Mike Papinski Lab"
title: "Mike Papinski Lab"
description: "Home of AI in Forex implementation"
meta_description: "Mike Papinski lab is a blog related to AI implementation in Forex market."
logo: 'assets/images/my_face_small.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'mp.papinski@gmail.com'
disqus: 'https-mikepapinski-github-io-sleek'
sharethis: "<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5dccaad3a96a11001267ff0b&product=sticky-share-buttons&cms=sop' async='async'></script>"

# Authors
authors:
  MikePapinski:
    name: MikePapinski
    display_name: Mike Papinski
    gravatar: my_avatar.png
    email: mp.papinski@gmail.com
    web: https://mikepapinski.github.io
    description: "Main author of Mike Papinski Lab."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge